### ISSUE TITLE
 # Interactional Buttons and Context Menu Commands Won't Work

### ISSUE THREAD

**Issue by The-User-1** [discohook/bot#15]
Interactional Buttons and Context Menu Commands Won't Work
it will always say "this interaction failed"

_Originally posted by @The-User-1 in https://github.com/discohook/discohook/issues/33#issuecomment-2449559389_

**Comment by shayypy** [comment]
You can provide more details on your issue in the support server, but this is not enough information to work with seeing as "it will always fail" is not proving to be reproducible behavior
