### ISSUE TITLE
“d.restore” command is broken

### ISSUE THREAD

**Issue by Vista1nik** [discohook/bot#5]
Hi there! `d.restore` command generates invalid link which leads to 520 error page.
![image](https://user-images.githubusercontent.com/16061243/130829282-35935f45-3b15-449f-a427-004acf98e789.jpeg)

**Comment by shayypy** [comment]
This is not an issue with the bot itself and thus you should go to [the Discord server](https://discohook.app/discord) for support with the site.

From #help:
> Hard refresh with `Ctrl/⌘ + Shift + R` about 10 times. If that does not work, use https://discoaid.netlify.app and follow the instructions there.
