### ISSUE TITLE
Unable to select roles for buttons

### ISSUE THREAD

**Issue by caeliamer** [discohook/bot#9]
Hi, when trying to add role buttons to a webhook, the drop down menu is not showing all of the roles on my server. It only shows the roles at the very top of the list. 

This is a recent problem. I used to be able to choose from all of my roles.

Any assistance with this problem is appreciated.

**Comment by ghost** [comment]
Wrong repository

You can search for roles by typing in a name, Discord limits the list to only 25 items or so
